# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

exclude: ["README.md", "License.md", "ivan-hanigan-cv.Rproj"]
highlighter: rouge

title: Ivan-Hanigan-CV
author:
  name: Ivan Hanigan
  email: ivan.hanigan@gmail.com
  github: ivanhanigan

# this is just too confusing 
  # kbroman says
  # A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  # REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH

# url: https://ivanhanigan.github.io
baseurl: /Ivan-Hanigan-CV

